const taskList = [
  // colored section => task_status,  bold black => title,  // name first after picture (left), + gender
  {
    address: 'asdaf fdaf dfad',
    all_day: true,
    category: {id: 1, name: 'Dog Walking'},
    city: 'Mohali',
    created_by: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
    description: 'ssdaf',
    end_date: '2022-05-16',
    end_time: '15:00:00',
    id: 1,
    price: '500',
    start_date: '2022-05-14',
    start_time: '13:42:00',
    sub_category: {category: 2, id: 1, name: 'House Cleaning'},
    task_status: 'pending for applicants',
    title: 'xyz',
  },
  {
    address: 'asdaf fdaf dfad',
    all_day: true,
    category: {id: 1, name: 'Dog Walking'},
    city: 'Test',
    created_by: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
    description: 'Test',
    end_date: '2022-05-16',
    end_time: '15:00:00',
    id: 2,
    price: '1500',
    start_date: '2022-05-14',
    start_time: '13:42:00',
    sub_category: {category: 2, id: 1, name: 'House Cleaning'},
    task_status: 'pending for applicants',
    title: 'Test',
  },
];

const chatlist = [
  {
    content: 'Hello',
    created_at: '2 hour ago',
    id: 1,
    receipent: 'ashwani2 kumar',
    receipent_details: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
    send_by: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
  },
  {
    content: 'Hello',
    created_at: '2 hour ago',
    id: 2,
    receipent: 'ashwani2 kumar',
    receipent_details: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
    send_by: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
  },
  {
    content: 'hi everyone',
    created_at: '2 hour ago',
    id: 3,
    receipent: 'ashwani2 kumar',
    receipent_details: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
    send_by: {
      first_name: 'ashwani2',
      id: 9,
      image: [Object],
      last_name: 'kumar',
      phone_no: '123456',
    },
  },
];
