const cities = [
  {id: 1, name: 'Jerusalem'},
  {id: 2, name: 'Tel Aviv-Yafo'},
  {id: 3, name: 'Haifa'},
  {id: 4, name: 'Rishon LeẔiyyon'},
  {id: 5, name: 'Petaẖ Tiqwa'},
  {id: 6, name: 'Ashdod'},
  {id: 7, name: 'Netanya'},
  {id: 8, name: 'Beersheba'},
  {id: 9, name: 'Bené Beraq'},
  {id: 10, name: 'Holon'},
  {id: 11, name: 'Ramat Gan'},
  {id: 12, name: 'Ashqelon'},
  {id: 13, name: 'Reẖovot'},
  {id: 14, name: 'Bat Yam'},
  {id: 15, name: 'Bet Shemesh'},
  {id: 16, name: 'Kefar Sava'},
  {id: 17, name: 'Herẕliyya'},
  {id: 18, name: 'Hadera'},
  {id: 19, name: 'Modi‘in Makkabbim Re‘ut'},
  {id: 20, name: 'Nazareth'},
  {id: 21, name: 'Lod'},
  {id: 22, name: 'Ramla'},
  {id: 23, name: 'Ra‘ananna'},
  {id: 24, name: 'Rahat'},
  {id: 25, name: 'Nahariyya'},
  {id: 26, name: 'Givatayim'},
  {id: 27, name: 'Hod HaSharon'},
  {id: 28, name: 'Rosh Ha‘Ayin'},
  {id: 29, name: 'Qiryat Ata'},
  {id: 30, name: 'Umm el Faḥm'},
  {id: 31, name: 'Qiryat Gat'},
  {id: 32, name: 'Eilat'},
  {id: 33, name: 'Nes Ẕiyyona'},
  {id: 34, name: '‘Akko'},
  {id: 35, name: 'El‘ad'},
  {id: 36, name: 'Ramat HaSharon'},
  {id: 37, name: 'Karmiel'},
  {id: 38, name: 'Afula'},
  {id: 39, name: 'Tiberias'},
  {id: 40, name: 'Eṭ Ṭaiyiba'},
  {id: 41, name: 'Qiryat Yam'},
  {id: 42, name: 'Qiryat Moẕqin'},
  {id: 43, name: 'Qiryat Bialik'},
  {id: 44, name: 'Qiryat Ono'},
  {id: 45, name: 'Or Yehuda'},
  {id: 46, name: 'Ma‘alot Tarshīḥā'},
  {id: 47, name: 'Ẕefat'},
  {id: 48, name: 'Dimona'},
  {id: 49, name: 'Tamra'},
  {id: 50, name: 'Netivot'},
  {id: 51, name: 'Sakhnīn'},
  {id: 52, name: 'Yehud'},
  {id: 53, name: 'Al Buţayḩah'},
  {id: 54, name: 'Al Khushnīyah'},
  {id: 55, name: 'Fīq'},
];
export default cities;
